apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: distributed-platform
type: Opaque
data:
  postgres-password: cG9zdGdyZXM=
  jwt-secret: ZGlzdHJpYnV0ZWQtcGxhdGZvcm0tc3VwZXItc2VjcmV0LWtleS10aGF0LWlzLWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmc=
