package com.platform.order.model;

public enum SagaStatus {
    STARTED, INVENTORY_PENDING, INVENTORY_DONE, PAYMENT_PENDING, PAYMENT_DONE,
    NOTIFICATION_PENDING, COMPLETED, COMPENSATING, COMPENSATION_COMPLETE, FAILED
}
